#ifndef IMAGEPROCESSING_H
#define IMAGEPROCESSING_H

#include <QObject>
#include <QImage>

#include "CDocument.h"

/**
  * Qt Object that acts as an interface to the Image Processing.
  * Auto-generated by clickable.
  */
class ImageProcessing: public QObject
{
  Q_OBJECT

public:
  ImageProcessing();
  ~ImageProcessing() = default;

  /**
    * Process an image containing a document. This will run 
    * the complete image processing. Use getContour(), 
    * getQuadrilateral() and getResult() to access 
    * (intermediate) results.
    */
  Q_INVOKABLE QString processImage(const QString & imageURL);
  /**
    * Get contour as a result of processImage(). The contour
    * is a polygone containing a list of points along the 
    * document edges.
    */
  //Q_INVOKABLE std::vector<cv::Point> getContour();
  /**
    * Get quadrilateral as a result of processImage(). The 
    * quadrilateral is a polygone containing exactly four
    * points representing the document corners.
    */
  //Q_INVOKABLE std::vector<cv::Point> getQuadrilateral();
  /**
    * Get document image as a result of processImage(). The 
    * document image contains the rectified image section
    * inside the detected quadrilateral. The image processing
    * contains some image enhancements to improve contrast
    * among others.
    */
  //Q_INVOKABLE cv::Mat getResult();

private:
  DocumentScanner::CDocument m_document;
};

#endif
